-- apply changes
create table cytonic_snoops (
  id                            integer generated by default as identity not null,
  target                        smallint,
  created                       timestamptz not null,
  channel                       varchar,
  content                       varchar,
  constraint pk_cytonic_snoops primary key (id)
);

