-- apply changes
create table cytonic_chat
(
    id      bigint generated by default as identity not null,
    sender uuid not null,
    recipient uuid,
    sent_at timestamptz not null,
    channel varchar(16),
    content varchar default '< Empty Message >' not null,
    constraint ck_cytonic_chat_channel check ( channel in
                                               ('ALL', 'PRIVATE_MESSAGE', 'INTERNAL_MESSAGE', 'PARTY', 'LEAGUE', 'MOD',
                                                'ADMIN', 'STAFF')),
    constraint pk_cytonic_chat primary key (id)
);

create table cytonic_reports
(
    id uuid not null,
    reporter uuid not null,
    player uuid not null,
    resolved boolean default false not null,
    submitted_at timestamptz not null,
    type     varchar               not null,
    context jsonb,
    constraint pk_cytonic_reports primary key (id)
);

-- foreign keys and indices
create index if not exists idx_sender on cytonic_chat (sender);
create index if not exists idx_recipient on cytonic_chat (sender);
create index if not exists idx_sent_at on cytonic_chat (sent_at);
