name: Build Plugins

on:
  workflow_run:
    workflows: ["docker", "publish"]
    types: [completed]

jobs:
  trigger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if both workflows succeeded
        uses: actions/github-script@v7
        id: check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflows = ["docker.yml", "publish.yml"];
            const runs = await Promise.all(workflows.map(async (file) => {
              const res = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: file,
                per_page: 1,
              });
              return res.data.workflow_runs[0]?.conclusion;
            }));
            const allSuccess = runs.every(c => c === "success");
            core.setOutput("ready", allSuccess);

      - name: Trigger plugin workflows
        if: steps.check.outputs.ready == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/CytonicMC/CytonicBedwars/actions/workflows/docker.yml/dispatches \
            -d '{"ref":"main"}'
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/CytonicMC/CytonicLobby/actions/workflows/docker.yml/dispatches \
            -d '{"ref":"main"}'
