name: Build and push Docker Image
run-name: Deploy Docker Image by @${{ github.actor }}

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  CONFIG_TOML: ${{ secrets.CONFIG_TOML }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      CONFIG_TOML: ${{ secrets.CONFIG_TOML }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Write config.toml
        run: echo "${{ secrets.CONFIG_TOML }}" > ./config.toml

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble Jar
        run: ./gradlew -Dorg.gradle.jvmargs=--enable-preview assemble
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t cytosis -f docker/basic/Dockerfile .

      - name: Tag Docker Image
        run: docker tag cytosis ghcr.io/cytonicmc/cytosis:latest

      - name: Login to GHCR
        run: echo $GHCR_TOKEN | docker login ghcr.io -u CytonicMC --password-stdin

      - name: Push Docker Image
        run: docker push ghcr.io/cytonicmc/cytosis:latest

