name: Build and push Docker Image
run-name: Deploy Docker image to GHCR by @${{ github.actor }}

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      #      - run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble Jar
        run: ./gradlew -Dorg.gradle.jvmargs=--enable-preview assemble
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t cytosis -f docker/basic/Dockerfile .

      - name: Push Docker Image
        run: |
          docker login ghcr.io -u CytonicMC -p $GHCR_TOKEN
          docker push ghcr.io/CytonicMC/cytosis:latest

