name: Build Pull Request
run-name: Deploy to Maven Repository by @${{ github.actor }}
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - run: chmod +x gradlew

      - name: Publish
        run: ./gradlew -Dorg.gradle.jvmargs=--enable-preview --no-daemon publish
